### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 1000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "d20d8b54ef4b4137af99eb3583387db8",
  "accountNumber": "1000000000",
  "amount": 1000
}

### check transaction
GET http://localhost:8080/transaction/d20d8b54ef4b4137af99eb3583387db8
