### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber":  "1000000000",
  "amount": 10000
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "4a79962958ad4f719297acca2049c2f4",
  "accountNumber":  "1000000000",
  "amount": 20000
}

### check transaction
GET http://localhost:8080/transaction/9844a348c3124d4690c676020e737814
